### PR TITLE
Separate image config tests from more general lx-brand tests

### PR DESCRIPTION
**Pull request by chorrell**
Hi @askfongjojo,

I wanted run this PR by you. This changed splits out all the tests that validate how we build images (what packages we pre-install, verifying the MTOD and other image specific configurations) from the more general lx-brand tests.

With this change there would be `image-config` tests for for validating image builds and `common-lx`
tests are for broader lx-brand tests. For just testing lx-brand, all you'd need is to use the `common-lx` role. Each of the distro specific roles also could be excluded since they validate distro specific configs. Or they should at least, I'm going to review those and see what might need to be separated out into `common-lx`.

I also updated the properties_example.yml file with proper usage.

### CODE REVIEW

**Comment by chorrell** [comment]
Hmm, thinking about it now, it might be better to rename `common-config` to something like `image-config`

**Comment by chorrell** [comment]
Renamed. I'll update my initial comment so the context makes sense

**Comment by askfongjojo** [comment]
@chorrell - This makes sense. Let's maintain two sets of tests to target the test execution based on what's changed in the environment.

**Comment by chorrell** [comment]
Sounds good, merging!

**Pull request merged**
